[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd hatchmark-frontend && npm install"]

[phases.build]
cmds = ["cd hatchmark-frontend && npm run build"]

[start]
cmd = "cd hatchmark-frontend && npm start"
